enc:
  utm_zone: 33
  size: [20000.0, 5000.0]                                                  # width, height (east, north) window to consider map data from. Unit is distance in meters
  origin: [39000.0, 6956450.0]                                            # easting/northing origin in UTM zone matchin that of input .gdb data
  buffer: 0                                                               # int of dilation or erosion distance for geometries
  tolerance: 0                                                            # int of maximum tolerance distance for geometries
  layers: ["seabed", "land", "shore"]                                     # list(str...) of feature layers to load or show
  depths: [0, 5, 10, 20, 50, 100, 200, 350, 500]                          # list(int...) of depth bins for feature layers
  files: ["More_og_Romsdal_utm33.gdb"]                                              # seacharts source database name
  new_data: false                                                          # bool indicating if new files should be parsed
  raw_data: false
  border: false                                                           # bool for showing a border around the environment plot
  verbose: true                                                           # bool for status printing during geometry processing
  #origin_lla: [62.457464, 6.146678]                                       # origin in latitude longitude (degrees) for transformation purposes (NOT IMPLEMENTED YET)

display:
  show_figure: False # Whether or not to disable the seacharts figure/display
  dpi: 96
  anchor: "center"
  resolution: 1080
  fullscreen_mode: false
  colorbar_mode: true
  dark_mode: true